config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  #splash page
  get '/', to: 'pages#home'

  #sessions
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  # users
  get '/signup', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users', to: 'users#index'
  get '/users/:id', to: 'users#show', as: "user"
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'

  #movies
  get '/movies', to: 'movies#index', as: 'movies'
  get '/movies/new', to: 'movies#new'
  post '/movies', to: 'movies#create', as: 'new_movie'
  get '/movies/:id', to: 'movies#show', as: 'movie'



  #reviews
  get '/reviews', to: 'reviews#index', as: 'reviews'
  get 'movies/:id/reviews/new', to: 'reviews#new'
  get '/movies/:id/reviews', to: 'reviews#view', as:'movie_review'  
  post '/reviews', to: 'reviews#create', as: 'new_review'
  get '/reviews/:id', to: 'reviews#show', as: 'review'
  get '/reviews/:id/edit', to: 'reviews#edit', as: 'edit_review'
  patch '/reviews/:id', to: 'reviews#update'
  delete '/reviews/:id', to: 'reviews#destroy', as: 'delete_review'


end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :user_movies
	has_many :reviews
	has_many :users, :through => :user_movies
	has_many :users, :through => :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	has_many :reviews
	has_many :user_movies
	has_many :movies, :through => :user_movies
	has_many :movies, :through => :reviews
end

app/models/user_movie.rb
class UserMovie < ActiveRecord::Base
	belongs_to :user
	belongs_to :movie
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include MoviesHelper


end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	skip_before_filter :verify_authenticity_token
	
	def index
		@movies = Movie.all
	end


	def create
		@movie = Movie.new(movie_params)
		if @movie.save
			flash[:notice] = "Successfully created movie!"
			
			redirect_to '/movies'
		else
			flash[:notice] = "Error! Cannot create movie!"
		end
		
	end

	def show
		@movie = Movie.find_by_id(params[:id])
	end


	private

	def movie_params
		params.require(:movie).permit(:e_title, :j_title, :img_url, :synopsis)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	

	def index
		@reviews = Review.all
	end

	def new
		@review = Review.new 
		render :new_review
	end

	def create
		@review = Review.new(review_params)
		if @review.save
			flash[:notice] = 'review posted'
			redirect_to '/movies'
		else
			flash[:notice] = "error- review not posted"
		end
	end

	def show
		@review = Review.find_by_id(params[:id])
	end

	def edit
		@review = Review.find_by_id(params[:id])
	end

	def update
		@review= Review.find_by_id(params[:id])
		@review.update_attributes(review_params)
		redirect_to user_path(current_user.id)
	end

	def destroy
		@review = Review.find_by_id(params[:id])
		@review.destroy
		flash[:notice] = 'Successfully deleted review'
		redirect_to user_path(current_user.id)
	end

	private

	
	def review_params
		params.require(:review).permit(:title, :review, :user_id, :movie_id, :movie_name, :user_name)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id

  		redirect_to '/users/' + user.id.to_s
  	else
      flash[:notice] = "Incorrect email or password"
  		redirect_to '/login'
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	

	def index
		@users = User.all

	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "Successfully created account!"
			session[:user_id] = @user.id
			redirect_to '/users/' + @user.id.to_s
		else
			redirect_to '/signup'
		end
	end

  def show
  	@user = User.find_by_id(params[:id])
  	@reviews= @user.reviews
    if @user != current_user
      redirect_to current_user
    end
  end

  def edit
  	@user = User.find_by_id(params[:id])
  end

  def update
  	@user = User.find_by_id(params[:id])
  	@user.update_attributes(user_params)
  	redirect_to user_path(@user.id)
  end


private

	def user_params
		params.require(:user).permit(:full_name, :email, :user_name, :password, :password_confirmation, :about_me)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

	def current_movie
		@current_movie = Movie.find_by_id(params[:id])
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def login(user)
  	session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    !!current_user
  end

    def logout
    @current_user = session[:user_id] = nil
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AniKuma</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="/"><img class ="navIcon" src ="http://orig13.deviantart.net/90c3/f/2013/032/f/0/teddy_bear_pixel_icon_by_thewritingdragon-d5tggbz.gif" href ='/'><a class="navbar-text" href ="/">ani-Kuma</a>
        <button class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
        <li ><%= link_to "Movies", '/movies' %></li>
		    <li ><%= link_to "Profile", user_path(current_user) %></li>
		    <li><%= link_to "Log Out", logout_path %></li>
		  <% else %>   
		    <li><%= link_to "Log In", login_path %></li>
		    <li><%= link_to "Create Account", new_user_path %></li>
          <% end %>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<div class="jumbotron">
  <div class="container">
    <div class='col-md-2 webplayer'> 
    <!-- embedded web player -->
      <!-- <iframe src="https://embed.spotify.com/?uri=spotify%3Auser%3A1244275508%3Aplaylist%3A2vGp8wqYJgnQ2bOjSE1GO1" width="300" height="380" frameborder="0" allowtransparency="true"></iframe> -->
    </div>
  </div>
</div>	
<!-- flash messages -->
<div class='container'> 
  <% flash.each do |name, msg| %>
    <% if name == "error" %>
      <p class="alert-danger">
    <% else %>
      <p class="alert-success">
    <% end %>
      <small> <%= name.capitalize %>: <%= msg %> </small>
    </p>
  <% end %>
</div>
<div class='container'>
<%= yield %>
</div>
</body>
</html>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
<div class='container'> 
	<div class="row"> 		
		<div class="col-md-8 col-md-offset-2">
			<div class='panel panel-success'>
			<div class='panel-heading'>Movie info</div>
				<div class='panel-body'>					
					<div class='container'> 
						<div class='col-md-2'>
							<div class='panel panel-success'>
								<div class='panel-body'>
									<img class="movie_poster" src="<%= movie.img_url %>">
										<div class='panel-footer'> 
											<button>add to watchlist</button>
												<%= button_to "New Review", "/movies/#{movie.id}/reviews/new", method: :get,class: "btn btn-default" %>
										</div>
								</div>
							</div>
						</div>
							<div class='col-md-5'>
								<div class='panel panel-success'>
									<div class='panel-body'>
										<p><strong>English Title: </strong><%= link_to "#{movie.e_title}", movie_path(movie.id) %> </p>
										<p><strong>Japanese Title: </strong><%= movie.j_title %></p>
										<p><strong>Synopsis: </strong><%= movie.synopsis %></p>
									</div>
								</div>
							</div>					
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>


	

			  
			

app/views/movies/new.html.erb
<div class='row'>
	<div class='container'>
		<div class='col-md-8 col-md-offset-2'>
			<div class="panel panel-default">
				<h1>new movie!</h1>

				<%= form_for :movie, url: '/movies' do |f| %>
				 
				  <p>English Title: <%= f.text_field :e_title %></p>
				  <p>Japanese Title: <%= f.text_field :j_title %></p>
				  <p>Synopsis: <%= f.text_area :synopsis %></p>
				  <p>Movie poster Url: <%= f.text_field :img_url %></p>

				  <p><%= f.submit "Submit" %></p>

				<% end %>
		</div>
	</div>
</div>

app/views/movies/show.html.erb
<div class='row'>
	<div class='container'>
		<div class='col-md-8 col-md-offset-2'>
			<div class="panel panel-default">
			<div class='panel-heading'>Movie info</div>
			<div class="panel-body">
			<div class='col-md-3'> <img class="movie_poster" src="<%= @movie.img_url %>" size="300px">
			 </div>
			<div class='col-md-8 col-md-offset-1'>
				<div class="panel panel-default">
				  <div class="panel-body">
				  	<p><strong>English Title:</strong> <%= @movie.e_title %></p>
					<p><strong>Japanese Title: </strong><%= @movie.j_title %></p>
					<p><strong>Synopsis: </strong><%= @movie.synopsis %></p>
				  </div>
				</div>
		  
			</div>
			</div>
			<div class='panel-footer'> 
			<%= button_to "New Review", "/movies/#{@movie.id}/reviews/new", method: :get,class: "btn btn-warning" %>
			<button class='video_button btn btn-default'> Watch now</button>
			</div>
			</div>
			<div class='col-md-6'> 
				<div class='video_player'> 
					<% if @movie.id == 1 %>
						<% video_id = '0B82YkbmbDGjzWC16RTBhUExCdjA' %>
					<% elsif @movie.id == 2 %>
						<% video_id = '0B82YkbmbDGjzamJxNDl3MXl4M0E' %>
					<% elsif @movie.id == 3 %>	
						<% video_id = '0B82YkbmbDGjzRGpJbl9scUdMekk' %>
					<% elsif @movie.id == 4 %>
						<% video_id = '0B82YkbmbDGjzNDJfRU9lSnVlT1U' %>
					<% elsif @movie.id == 5 %>
						<% video_id = '0B82YkbmbDGjzb3d0MkVJY3FZN3c' %>	
					<% elsif @movie.id == 6 %>	
						<% video_id = '0B82YkbmbDGjzbFJKRmNFOXdkLVU' %>
					<% elsif @movie.id == 7 %>	
						<% video_id = '0B82YkbmbDGjzdkVmTExab041aGs' %>
					<% elsif @movie.id == 8 %>	
						<% video_id = '0B82YkbmbDGjzS2ozOHJOdGJXYUU' %>
					<% elsif @movie.id == 9 %>	
						<% video_id = '0B82YkbmbDGjzS0RfRXk4V05XMVU' %>
					<% elsif @movie.id == 10 %>	
						<% video_id = '0B82YkbmbDGjzcEJZV19Nd1NzSDQ' %>	
					<% end %>



					<iframe src="https://drive.google.com/file/d/<%= video_id %>/preview" width="640" height="344" allowfullscreen></iframe>
				</div>	
			</div>	
		</div>	
	</div>
</div>

<div class='row'> 
	<div class='container'>
		<div class='col-md-8 col-md-offset-2'>
			<div class="panel panel-default">
			<div class='panel-heading'>User Reviews</div>
			  <div class="panel-body">
				<% @movie.reviews.each do |review| %>
				<p> <strong> User Name: </strong><%= review.user_name %></p>
				<p> <strong> Review title: </strong><%= review.title %></p>
				<p> <strong> Review: </strong><%= review.review %></p>
				<hr>
				<% end %>

			  </div>
			</div>
		</div>
	</div>
</div>

app/views/movies/watch/video_player.html.erb
<iframe src="https://drive.google.com/file/d/0B82YkbmbDGjzWC16RTBhUExCdjA/preview" width="640" height="480"></iframe>

app/views/pages/home.html.erb
<div class="col-md-8 col-md-offset-2 ">

	<div class='col-md-10 col-md-offset-1'>
      <form class="search">
        <div class="form-group">
         <input type="text" class="form-control search_bar" placeholder="Search for a Movie">
         <button class="btn btn-warning pull-right" id="search_button">Submit</button>
         </div>
      </form>
	</div>

</div>


<div class="row">
	<div class='container'> 
		<div class= "col-md-3 "> 
			<div class='panel panel-default'>
			<div class='panel-heading'> <p>suggested movies</p></div>
				<div class='panel-body'>
					
				</div>
			</div>
			
		</div>
		<div id='420' class= "col-md-7 col-md-offset-1">
			<div class='panel panel-default'>
				<div class='panel-heading'>Rendered Search Results</div>
				<div class='panel-body'>
					<div id='rendered_search'>
						
					</div>
					
				</div>
				
			</div>
			
			



		</div>
	</div>

</div>

app/views/reviews/edit.html.erb
<div class='container'>
	<div class='col-md-8 col-md-offset-2'>
	<div class ='panel panel-warning'>
		<div class='panel-heading'>
			<strong >Edit Your review:</strong>
		</div>
		<div class='panel-body centered_block'>
			<%= form_for @review do |f| %>
		  <p><strong>Title: </strong>
		    <%= f.text_field :title, placeholder: "Title" %></p>
		   
		    <p><%= f.text_area :review, placeholder: "Review", class: "about_me_form" %></p>
		    <%= f.submit "Save Review", class: "btn btn-default" %>
		  <%= button_to "Back", review_path, method: :get, class: "btn btn-danger " %>
		  
		  
		<% end %>
		</div>
	</div>
	</div>
</div>

app/views/reviews/index.html.erb
reviews#index

app/views/reviews/new_review.html.erb
<div class='container'>
	<div class='col-md-8 col-md-offset-2'> 
		<div class="panel panel-warning" >
		<div class="panel-heading">
			Create a New Review:
		</div>
		<div class="centered_block">
		

		<%= form_for @review, url: new_review_path do |f| %>
		<br>
			<p>Movie Title:  <%= f.text_field :movie_name, value: current_movie.e_title %></p>	
		    <p>Review Title: <%= f.text_field :title, placeholder: "Title" %></p>
		    <p><%= f.text_area :review, placeholder: "Review", class: "about_me_form" %></p>
		  <%= f.hidden_field :user_id, value: current_user.id%>
		  <%= f.hidden_field :user_name, value: current_user.user_name%>
		  <%= f.hidden_field :movie_id, value: params[:id]%>
		  <p><%= f.submit "Create Review", class: "btn btn-default" %></p>
		<% end %>
		
		</div>
		</div>	
	</div>
</div>		

app/views/users/index.html.erb
<h1>Users#index</h1>

<p>signed in as: <%= current_user.user_name %> </p>
<p>full name: <%= current_user.full_name %> </p>
<p>email: <%= current_user.email %> </p>
<p>created at: <%= current_user.created_at %> </p>
<p>about me: <%= current_user.about_me %> </p>

app/views/users/new.html.erb
<div class='row'>
	<div class='container'>
		<div class='col-md-8 col-md-offset-2'>
			<div class="panel panel-default">
			<div class='panel-heading'> <h1>Signup!</h1></div>
			<div class='panel-body centered_block'> 

			<%= form_for :user, url: '/users' do |f| %>
			 
			  <p>Full Name: <%= f.text_field :full_name %></p>
			  <p>Email: <%= f.text_field :email %></p>
			  <p>Username: <%= f.text_field :user_name %></p>
			  <p>Password: <%= f.password_field :password %></p>
			  <p>Password Confirmation: <%= f.password_field :password_confirmation %></p>
			  <p><%= f.submit "Submit" %></p>

			<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class='container'> 
	<div class="row">
		<div class='col-md-10 col-md-offset-1'>
			
			<div class='panel panel-primary'>
					<div class="panel-heading"><%= @user.user_name %></div>
				<div class='panel-body'> 
					<div class="col-md-3">
						<div class='panel panel-primary'>
						  <div class='panel-body'>
							<p><img src="http://placehold.it/125x175"></p>
						  </div>
						</div>
					</div>

					<div class='col-md-3'>
						<div class="panel panel-primary">
							
						  <div class="panel-body"> 
							<p> <strong> welcome: </strong><%= @user.full_name %> </p>
							<p> <strong> created on: </strong><%= @user.created_at.strftime("%b. %d %Y") %> </p>
							<button>edit</button>
							</div>
						</div>
					</div>

					<div class='col-md-5 col-md-offset-1 '>
						<div class="panel panel-primary"> 
							<div class='panel-body'> 
								<p> <strong> About me: </strong><%= @user.about_me %> </p>
								<div id="about_me_box">							
										<%= form_for @user, url: {action: 'update'} do |f| %>
										<%= f.text_area :about_me, class: "about_me_form" %>
										<%= f.submit "Save", class: "btn btn-success" %>
										<% end %>
								</div>								
								<button id="about_me">edit</button>
							</div>	
						</div>	
					</div>
				</div> 
			</div>
		</div>	
	</div>
</div>

<div class="container"> 
	<div class="row"> 
		<div class='col-md-6 col-md-offset-1'> 
			<div class="panel panel-info">			
			  <div class="panel-heading"> Recent Comments</div>
				<div class="panel-body">  
					<% @reviews.each do |review| %>
						<div class='panel panel-info'>
							<div class='panel-body'> 
								<div class='col-md-6'>
								<p><strong>Movie: </strong> <%= link_to "#{review.movie_name}", "/movies/#{review.movie_id}" %></p> 
								<p><strong>Title: </strong> <%= review.title %></p>
								<p><strong>Review: </strong> <%= review.review %></p>
								</div>
							</div>
								

								<div class='panel-footer'> 
								<p><%= button_to 'Edit Review', edit_review_path(review.id), method: :get, class: "btn btn-warning" %><%= button_to 'Delete Review', delete_review_path(review.id), method: :delete, class: "btn btn-danger" %></p>
								</div>
						</div>
					<% end %>
				</div>
					
			</div>
		</div>
	
		
		<div class="col-md-3 col-md-offset-1">	
	 		<div class="panel panel-info">
	 		<div class='panel-heading'> <p> watch list here </p></div>
				<div class="panel-body">				 
					
					<p>not implemented</p>
				</div>
			</div>
		</div>
	</div>
</div>
 